Feature/ffmpeg azure function
EastBridgeSoftwareSolutions/MyCoronaTimeLapse pull request #6
Opened 2020-05-02 21:12 UTC by Xiliath

2020-05-09 12:52 UTC, flixcor requested changes

2020-05-09 12:52 UTC, flixcor commented on COGIF-19.AzureStorage/Extensions.cs
> +            foreach (var item in blobContainer.ListBlobsSegmentedAsync(null).Result.Results)
.result? Kan je dit niet awaiten?

2020-05-09 12:52 UTC, flixcor commented on TimeLapseWebHost/FileStore.cs
> +            try
Is de enige manier met try catch? Kan je niet de items in de container listen en checken of ie er tussen zit?

2020-05-09 12:52 UTC, flixcor commented on TimeLapseWebHost/FileStore.cs
> +                if (e.RequestInformation.HttpStatusCode == (int)HttpStatusCode.NotFound)
Waarom deze check? Je retourneert sowieso false, toch?

2020-05-09 12:52 UTC, flixcor commented on TimeLapseWebHost/FileStore.cs
> +            return new Uri($"{baseUrl}/{id}/{resourceId}{sasToken}");
Nice!

2020-05-13 09:32 UTC, flixcor commented on TimeLapseWebHost/FileStore.cs
> +            return new Uri($"{baseUrl}/{id}/{resourceId}{sasToken}");
O trouwens, misschien de baseurl nog FF configurabel maken :)

2020-05-13 19:25 UTC, Xiliath commented on COGIF-19.AzureStorage/Extensions.cs
> +            foreach (var item in blobContainer.ListBlobsSegmentedAsync(null).Result.Results)
Ik had hier wat moeite mee toen ik een await foreach wou implementeren. maar dit kan idd beter, ik ga even kijken. (sta open voor suggesties)

2020-05-13 19:56 UTC, merged